name: Nuitka Build

on:
  push:
    branches:
      - main  # 触发条件：推送到 main 分支时运行
  pull_request:
    branches:
      - main  # 触发条件：针对 main 分支的 PR 时运行

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 拉取代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 指定 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka  # 安装 Nuitka

      - name: Compile with Nuitka
        run: |
          python -m nuitka --onefile --windows-icon-from-ico=logo.ico --output-dir=dist main.py
          # --onefile: 生成单个可执行文件
          # --windows-icon-from-ico: 指定图标文件
          # --output-dir: 输出目录

      - name: Package the executable
        run: |
          cd dist
          Compress-Archive -Path main.exe -DestinationPath MyProgram.zip  # 将 .exe 打包为 zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # 使用 v4 版本
        with:
          name: MyProgram
          path: dist/MyProgram.zip  # 上传打包后的文件
